name: Build RPM
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install rpmbuild
      run: sudo apt-get install rpm && sudo apt-get install createrepo

    - name: Run build
      run:
        |
        cd rpm-builder/
        php pack.php
        php update_repo.php