name: Build RPM
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run:
        |
        cd rpm-builder/
        composer install --prefer-dist --no-progress

    - name: Run build
      run:
        |
        cd rpm-builder/
        php pack.php