name: Build RPM
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'centos:latest'

    steps:
    - uses: actions/checkout@v3

    - name: Install rpmbuild
      run:
        |
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        dnf distro-sync -y
        yum install -y createrepo rpm-build rpm-sign wget gcc python3 yum-utils
        yum install php -y
        yum install ftp-upload -y

    - name: Run build
      run:
        |
        cd rpm-builder/
        php pack.php
        RPM_FILE="$(php update_repo.php)"
        ls -la
        ftp-upload --verbose --binary --ls --passive --tmp-samedir --ignore-quit-failure -h $FTP_HOST -u $FTP_USERNAME --password $FTP_PASSWORD $RPM_FILE
        echo "Uploaded file complete"