name: Build RPM
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Go to RPM build folder
      run: cd ./rpm-builder

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run build
      run: php pack.php