name: Build RPM
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'centos:latest'

    steps:
    - uses: actions/checkout@v3

    - name: Install rpmbuild
      run:
        |
        sudo add-apt-repository main
        sudo add-apt-repository universe
        sudo add-apt-repository multiverse
        sudo apt-get update
        sudo apt-get install rpm 
        sudo apt-get install dpkg-dev
        sudo apt-get install apache2
        sudo apt-get install -y createrepo

    - name: Run build
      run:
        |
        cd rpm-builder/
        php pack.php
        php update_repo.php